FROM grafana/grafana

ARG JQ_VERSION
USER root
RUN curl -o /usr/bin/jq -L https://github.com/jqlang/jq/releases/download/jq-${JQ_VERSION}/jq-linux-amd64 && chmod +x /usr/bin/jq
USER grafana
WORKDIR /var/lib/grafana/plugins
RUN wget https://github.com/yamcs/grafana-yamcs/releases/download/v2.2.2/yamcs-yamcs-datasource-2.2.2.zip
RUN unzip yamcs-yamcs-datasource-2.2.2.zip && rm yamcs-yamcs-datasource-2.2.2.zip
WORKDIR /home/grafana
COPY ./grafana/setup.sh ./setup.sh
COPY ./grafana/import.sh ./import.sh
COPY ./grafana/scsat1_ini.json scsat1_ini.json
