# FROM debian
FROM python:latest
ARG OPENJDK_VERSION

ARG YAMCS_URL
ARG YAMCS_VERSION

RUN apt-get update&& apt-get install -y \
    nano \
    systemd \
    alien \
    ${OPENJDK_VERSION}

# Yamcs Download
RUN wget -O yamcs_install.x86_64.rpm ${YAMCS_URL} \
    && alien --script -d -k yamcs_install.x86_64.rpm \
    && rm yamcs_install.x86_64.rpm

COPY mcs_install.sh ./mcs_install.sh
RUN chmod +x ./mcs_install.sh
ENTRYPOINT ./mcs_install.sh
