
#+title: SC-Sat1 MCS and Grafana with Docker
This directory contains all the necessary files to run SC-Sat1 MCS and Grafana in Docker containers.
* Features
    * Build and run Docker containers for SC-Sat1 MCS and Grafana.
    * Start the server to access SC-Sat1 MCS and Grafana.
* Getting Started
** Starting Docker
    * Build and Run the Containers
    To create and start the containers for SC-Sat1 MCS and Grafana, run the following command:
    #+begin_example
    docker-compose up -d
    #+end_example

    * Running with Persistent Data
    If you want to enable data persistence, run the following command:
    #+begin_example
    docker-compose -f compose.yaml -f compose.override.yaml up -d
    #+end_example

    * Accessing the Services
        * SC-Sat1 MCS: [[http://127.0.0.3:8090/]]

        * Grafana: [[http://127.0.0.3:3000/]]

** Grafana Setup
    * First Time Setup
    Create service account, generate token, and configure datasource for Yamcs
    #+begin_example
    docker exec -it grafana bash
    source setup.sh
    #+end_example

    * JSON Import
    Read a JSON file to create dashboards and folders in Grafana
    #+begin_example
    bash import.sh <JSON_FILE>
    #+end_example
    
    * Subsequent Runs
    Use the preconfigured service account and token.
    #+begin_example
    source .grafana_profile 
    #+end_example
    
* Container operations
    * Stopping and Removing the Containers
    To stop and completely remove the containers,, run the following command:
    #+begin_example
    docker-compose stop
    #+end_example

    * Stopping and Removing the Containers
    To stop and completely remove the containers, run the following command:
    #+begin_example
    docker-compose down
    #+end_example

    * Stopping Individual Services
    To stop SC-Sat1 MCS only:
    #+begin_example
    docker stop yamcs
    #+end_example

    To stop Grafana only:
    #+begin_example
    docker stop grafana
    #+end_example

* Configuration Options
Additional configurations can be customized in the [[docker/.env][.env]]
    * Host Access IP:
    #+begin_example
    MY_IP={YOUR_IP_ADDRESS}
    #+end_example
    * Yamcs Version:
    #+begin_example
    YAMCS_VERSION={VERSION_NUMBER}
    #+end_example
    * OpenJDK Version:
    #+begin_example
    OPENJDK_VERSION={OPENJDK_VERSION}
    #+end_example
    * JQ Version:
    #+begin_example
    JQ_VERSION={JQ_VERSION}
    #+end_example
